### ISSUE TITLE
How to import the base model

### ISSUE THREAD

**Issue by pilot22** [zakodium/adonis-mongodb#100]
Hello.
I don't understand how to import and extend the BaseModel interface

Right now im getting an error while doing this:

```
import { Model } from '@ioc:Zakodium/Mongodb/Model'

export default class User extends Model {
  public static collectionName = 'users'

  public name: number
}
```

> E_IOC_LOOKUP_FAILED: Cannot resolve "Zakodium/Mongodb/Model" namespace from the IoC Container"

```
import { MongodbModel } from '@ioc:Zakodium/Mongodb/Odm'

export default class User extends MongodbModel {
  public static collectionName = 'users'

  public name: number
}
```

> Class extends value undefined is not a constructor or null

Help please

**Comment by pilot22** [comment]
Resolved by:
```
import { BaseModel } from '@ioc:Zakodium/Mongodb/Odm'

export default class User extends BaseModel {
  public static collectionName = 'users'

  public name: number
}
```

**Comment by stropitek** [comment]
Note that you don't have to set a `collectionName`, it will be generated from the constructor's name.
