### ISSUE TITLE
Please do not stop working on this project.

### ISSUE THREAD

**Issue by azabroflovski** [zakodium/adonis-mongodb#101]
Hi, I am writing a project in a bunch of adonis + mongodb, I came across your project, please do not give up this case. This is the only normal solution for me 😁

Good luck, guys!

![Cat](https://user-images.githubusercontent.com/33807338/131251384-58ba660a-154c-4674-b0b5-f73b402c2585.png)

**Comment by targos** [comment]
Thank you for the kind words. We are definitely not going to stop working on this project :)
