### ISSUE TITLE
Pagination features missing

### ISSUE THREAD

**Issue by maasencioh** [zakodium/adonis-mongodb#108]
Normally during pagination is necessary to sort, skip and limit a query. A proposed API could be

```ts
const cursor= Model.query({}).sort('field', 1);
const total = await cursor.count();
const items = await cursor.skip(10).limit(10).all();
```

**Comment by targos** [comment]
@maasencioh proposed implementation at https://github.com/zakodium/adonis-mongodb/pull/112
