### ISSUE TITLE
Invoke command error

### ISSUE THREAD

**Issue by vkaelin** [zakodium/adonis-mongodb#18]
Hi!
When I run the invoke command I get the following error: 

```
(node:3160) UnhandledPromiseRejectionWarning: Error: Template file not found: C:\code\LeagueStats\server-new\node_modules\@zakodium\adonis-mongodb\templates\mongodb.txt
```

I fixed it by changing some values in package.json but I'm not sure it's the right thing to do:

```
"templates": {
  "basePath": "./templates",
  "config": [
    {
      "src": "config/mongodb.txt",
      "dest": "mongodb"
    }
  ]
},
```

I took some inspiration from the official Redis package: https://github.com/adonisjs/redis/blob/develop/package.json#L103

**Comment by stropitek** [comment]
Hello,

Thank you for your feedback. This package is under active development and is not yet stable. We have updated our readme to reflect that.

Also this provider only works for adonis v5, that is probably why you encountered an error.

**Comment by vkaelin** [comment]
Hi! 
Used it with the last Adonis 5 release

**Comment by targos** [comment]
Are you sure that you are on the most recent version of Adonis 5?

**Comment by vkaelin** [comment]
Just saw that creating a fresh adonis app doesn't take all the greatest packages version, my bad!

Thanks for this package, looks really promising! 

Here was my package.json, just in case:

```
"devDependencies": {
    "@adonisjs/assembler": "^2.1.5",
    "adonis-preset-ts": "^1.0.4",
    "eslint": "^7.10.0",
    "eslint-plugin-adonis": "^1.0.15",
    "pino-pretty": "^4.2.1",
    "typescript": "^4.0.3",
    "youch": "^2.1.1",
    "youch-terminal": "^1.0.1"
  },
  "dependencies": {
    "@adonisjs/ace": "^6.9.4",
    "@adonisjs/core": "^5.0.0-preview-rc-1.12",
    "@adonisjs/fold": "^6.4.1",
    "@zakodium/adonis-mongodb": "^0.3.0",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19"
  }
```
