### ISSUE TITLE
Correct mongodb typing

### ISSUE THREAD

**Issue by targos** [zakodium/adonis-mongodb#5]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6a3556a1bc18bc2650612009011e5f0df4533125

Introduced a bug when we explicitly type options with: `const options: FindOneOptions<T> = {}`
and call `collection.findOne<T>({}, options)`

**Comment by targos** [comment]
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQgGzQUwMY2BAOwBo4AxYNGTKARQFdqBPE8ggEwHkDMOw9CAznAC+cAGZQIIOAHIQhAOYQ2AIxkBuALAAoHWLoFc+AnAWYYqDDn4EAPABUAfAAoAlAC4U6LEcIPHiDpwcFDmdFAmCKIAhkKWPjb+WtrCOjoA9OlwvDZCYLECmGxwwARopZieBBBwYJIqWCA6sYyG4ga+JmKlbACM-s7dlNSe5MO0DFCM-q6B2sHYgvCLVp1wALym5vHWxgOuycGhMOEmKwnGAHTd7FyYgxRUUCRI5SDAMJ4ArCIHOqm6bSZbJ8YxCNg4NDRULFADuHwAFltuFBgNg4NF2CUCB9gNFygAvIqeaiSKDNAStdH6Qw2cQ9ABMAyGT1Gj2o9CYMzmCyWcHOu0IGy2Fm8grsTjch35fIgoMEbNu3ByYP8wteoA+3xE0uOpxlqxs1x6dwe4xIctyfxSaSBWRVgjgEOwUJhcHhMCRZhRaIxWJg0QA1pgTKUMVAFHQQCGYAISVAyRSqe1acZ6ewAMzM9lQNnjTlTfwW+UEAQAfkVnGVJYE3IQQRlpeWYrWmzMosNe0l1qOYQiBouhGNSvuLOoxatyQBOlKTzE0WwmDgABFogGeSU2J4BDBUQQFNKAG74hhVKMqahT203Pq2VcBlxIYBb2RUHcyEjHtCnuC9X56Rk7zXaJH03TwZDfGAPzgL8fz-YRXAAzMgIfZwnxfCDMHfT8T0qX8RBeOA3i1OAvhIOoIAAK3FTx0M8eD-20IA

**Comment by Xstoudi** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48300

**Comment by Xstoudi** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48572#issuecomment-709966385

Seems to be the only proposal to fix this problem.
