### ISSUE TITLE
"ace invoke" instead "ace configure" 

### ISSUE THREAD

**Issue by rodolforamos** [zakodium/adonis-mongodb#52]
Just change on the installation instruction "ace configure" to "ace invoke". cheers

**Comment by targos** [comment]
Why? They are two aliases for the same command. I think configure is more clear about what it does.

**Comment by rodolforamos** [comment]
@targos last night on a fresh installation i've tried "configure" and got message that "command not found", just because that.

**Comment by targos** [comment]
Configure is available in the latest version: https://github.com/adonisjs/assembler/blob/4cbd842b009018fb0bdf3daa843d6baa9244b357/commands/Invoke.ts#L17
