### ISSUE TITLE
toJSON() method for Models ?

### ISSUE THREAD

**Issue by vkaelin** [zakodium/adonis-mongodb#53]
Hey 👋

As explained on Discord, here is the issue to explain the actual missing feature.

Currently, when we return a plain Model via JSON for example, we get the full Object. For example:

```js
{
  $collection: {},
  $currentData: {},
  $isDeleted: false,
  $options: {},
  $originalData: {},
}
```

It would be useful to have a method, for example ``toJSON()`` to get only the values inside the ``$currentData`` key.

Thanks a lot for this great package!

**Comment by targos** [comment]
A `toJSON()` method that returns the value of `$currentData` SGTM. Would you like to open a PR ?

**Comment by vkaelin** [comment]
I can try yes!
